language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - 51101661@qq.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- export BUILD_NAME=accountserver-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
env:
  global:
  - secure: SPx+AgKhrJBqhtf6uKv99i8U8Su4S5tcQn6QFNp7cVkzwmr9CS0K3hltihBcxyhzfNIkaPioZDO0eNkBn3WNZXlDvKTie+XUuVGDz0ziSKHvKHY25k/2ZhbMnzBlneO57ji63fPyTS0VD1ZiM6rY7ZQ6dLdQNHhQTInRpZ8aqmhEtizonURhMbNgYDXWgWaWbiTwiujMqvJ0uWMRZEZcQAW+AzFvYVZHV++GjMekD3ux+2H1FiDWUTE8XdMMlwSA7AlsOJO1UDWmGqbfyTWUsFbaOqnXI9NM2zk0UcR0Qs/UGv4wF8Rm9wOyl0bZdGZQiLt0WKARzed0mRDKZQEBF6ko9gX0oV9PI7P+FemH2Rar/NxY77eE6aGpwFsMgedC33QyQ2S+NUK+k/8mhH5owkWwGhdmLiPdo/10HigBdBhYavpcpSTkZNbD2qVM92hV9gj/BMKSicDuDCpgKJiY2Uh9VpptvLrZRS1PC97p1sssVwVnTNTUMvHhDc6t45Y+IPd5YWkDrDbcIajHh4VNn7b/XHie4OdpClsEOSJQ09j5sbfO7dJ0xNoHJxcSKivEHW6l+6DRyMW9baUJb863XX1+ZRR/mqIN5ilnkqOUCsVIFTXLxYouVb3BWoiFpn/UPrpn1sZ77IgkPPGcyWkl2I4n8mvuTcll+P2qllKEcg4=
  - secure: ODMiuVTsZnAGZyGohaSDHrqiCuaFnWVJvcrq8uoLCt9v4+fSY2UbrmMPOmkRQEAqRPhqaJD0Euzuyfee2r/BtsmbYZ1nZ/Rm9XRPp/yVxDWgu9MqKDMf2YqmXwpaK/H4iXfFUIhn8lgzDfAFSDvuumRzCaOHRUIWpuoPzUS+8CddXIVp9bKKptkARaVMfvnKlKEGiLeLnPgjwJjoVcpg/Up/IDeL7S03npo9UIQrJTp5U6AnH4bGiP0ZbbzyaQmJf9ZymAfFPs7vwBzEOD/rn1P90Eammh/OXSNybSkpCfXnuwydVxn2nnyzLBEchOi0P8GOQgU7bnu6emw71Ke1EUtNaFbRb12v+M8iNRlEyRGLROGkEEJWl/TdUrvd7ABcVLO/tFpEyWY3ZdMdkOHLDk7d9KEbcQMzSAfKNrM9dzKbX9Fth/hL3ADvV/lUTsVtsqa6imdKFW+DQmpDguU/RbiJRCO+OMVm2uLGYJgwGBoKuZxDMiCPddsGl1sfjRp1pN5KywS/GEW2g0dLR4sUTIOnCYUXH8jtJOfCwFDnyiKgOBDyhsls/NNCnnpEvKt4c7CAi34FP5XPAf2nOR0WM8K8rTOlwQVxFpMNjClSvw3rqRtFIEY48Tgx3lwMOvLq4If5W4/liJ2cGW2n1ifGWQb6wQdeWxYwg8aK6GrBbFI=
  - secure: GI6OrYkqVIdRqebK6PsDvipbPxjXsFKFRMEIGULdlB083KwG5KwZJioedRyuZTknC9ZpnnLSe4EKsLVT8+ohXC9npQVfIyPrv7kz+LIOfJrSCp81/npILXy/XH98+m7iTZi58BcsRZRzi2ELCc1JBR/dD8ejwIsz0wJSJ4mrQQ8QRXfBAZbUL9/riL1rNW8KMzrUGqHb9aw/X7IY0P+GyOeL4rwtVk+R3Lza86tPc1diFY0NJ/UOFl8iDXL0lkLwOaWgekiv9wzmwcoJgxk7IRBAyKyZz44MwHAuE0RncfctMmz1oPDolJlb6NwIDFLpuGvfoGftHbdg/nWdP5zbPxTRqTquaiUjdevA2tuQvi1EFkWQhN+tU9A2R06tO2ICWRUVjra8HA8nokjvNWiotsTPYGfZbzuUVPbBgC//srhspNCNDeU7HzBNWyom5xHS0sy+xDZ6NgNyZJpilxm6VP0Z08bRxovZDyDpqDkjouV8BTGxCLeV/o7fvfc3CNlVNRWd3kydvrBuBujOwm+kskIiEt7gC6LHCCfnAKtsBZnYXwrn+d74/b44ft2EU8LoJ8eFv8z/D63CbqP7miz2zNDBgS4YmLJrVh3M70/t3mNvm4BE2faz83d220tOQ5V3m6lkWEPHwpThwNHZzqS3weGOBqVOuCzDoY26IPdomuY=
